<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="L-MAA-25005271" name="com.friday.test.Fridayskillassesment.convertstringtoJSON_Negative" tests="2" failures="0" timestamp="1 Nov 2018 04:18:12 GMT" time="0.011" errors="2">
  <testcase name="TC_06_negative" time="0.003" classname="com.friday.test.Fridayskillassesment.convertstringtoJSON_Negative">
    <error type="java.lang.AssertionError" message="Street name is wintralle 3 berlin - Street name should have string values with no numbers between expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Street name is wintralle 3 berlin - Street name should have string values with no numbers between expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.friday.test.Fridayskillassesment.processor.Dataparser.splitdata(Dataparser.java:45)
	at com.friday.test.Fridayskillassesment.convertstringtoJSON_Negative.TC_06_negative(convertstringtoJSON_Negative.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:46)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:37)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]>
    </error>
  </testcase> <!-- TC_06_negative -->
  <testcase name="TC_05_negative" time="0.008" classname="com.friday.test.Fridayskillassesment.convertstringtoJSON_Negative">
    <error type="java.lang.AssertionError" message="House number is Blaufeldweg - house number should have numeric values expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: House number is Blaufeldweg - house number should have numeric values expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.friday.test.Fridayskillassesment.processor.Dataparser.splitdata(Dataparser.java:37)
	at com.friday.test.Fridayskillassesment.convertstringtoJSON_Negative.TC_05_negative(convertstringtoJSON_Negative.java:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:46)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:37)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]>
    </error>
  </testcase> <!-- TC_05_negative -->
</testsuite> <!-- com.friday.test.Fridayskillassesment.convertstringtoJSON_Negative -->
